project:
  type: book
  output-dir: docs
  
book:
  title: "Análiside Datos con R y Python"
  author: "RICUIB"
  date: " febrero 2025"
  subtitle: "Guía para el Análisis de Datos con R y Python"
  
  chapters:
    - index.qmd
    - intro.qmd
    - part: MicrocreditoI.qmd
      chapters: 
        - dia1.qmd
        - dia2.qmd
        - dia3.qmd
        - dia4.qmd
        #- 01_Modulo_R.qmd
        #- 02_Modulo_Exploracion.qmd
        #- 03_Modulo_Estadistica.qmd
        #- 04_Modulo_Informes.qmd
        #- 05_Modulo_Graficos.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: materia
      dark: darkly
    css: custom.css
    cover-image: 100_prisoners_boxes_fixed.png
    toggle: true


  pdf:
    documentclass: scrreprt
   
editor: visual
lang: es
